// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using internLoanProjectAPI.Persistence.Contexts;

#nullable disable

namespace internLoanProjectAPI.Persistence.Migrations
{
    [DbContext(typeof(internLoanProjectAPIDbContext))]
    partial class internLoanProjectAPIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("internLoanProject.Domain.Entities.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ziraat Bankası"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Halkbank"
                        },
                        new
                        {
                            Id = 3,
                            Name = "VakıfBank"
                        },
                        new
                        {
                            Id = 4,
                            Name = "İş Bankası"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Garanti BBVA"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Yapı Kredi"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Akbank"
                        },
                        new
                        {
                            Id = 8,
                            Name = "QNB"
                        },
                        new
                        {
                            Id = 9,
                            Name = "DenizBank"
                        },
                        new
                        {
                            Id = 10,
                            Name = "TEB"
                        });
                });

            modelBuilder.Entity("internLoanProject.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerType")
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("internLoanProject.Domain.Entities.Identity.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("internLoanProject.Domain.Entities.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasFilter("[CustomerId] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("internLoanProject.Domain.Entities.LoanApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("LoanCalculationId")
                        .HasColumnType("int");

                    b.Property<int>("LoanProductId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LoanCalculationId")
                        .IsUnique();

                    b.HasIndex("LoanProductId");

                    b.ToTable("LoanApplications");
                });

            modelBuilder.Entity("internLoanProject.Domain.Entities.LoanCalculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoanProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyInstallment")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBsmv")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalInterest")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalKkdf")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPayment")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LoanProductId");

                    b.ToTable("LoanCalculations");
                });

            modelBuilder.Entity("internLoanProject.Domain.Entities.LoanProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerType")
                        .HasColumnType("int");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LoanTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxTerm")
                        .HasColumnType("int");

                    b.Property<decimal>("MinAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MinTerm")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("LoanTypeId");

                    b.ToTable("LoanProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BankId = 1,
                            CustomerType = 1,
                            InterestRate = 3.25m,
                            IsActive = true,
                            LoanTypeId = 1,
                            MaxAmount = 100000m,
                            MaxTerm = 24,
                            MinAmount = 5000m,
                            MinTerm = 3,
                            Name = "Öğrenci İhtiyaç Kredisi"
                        },
                        new
                        {
                            Id = 2,
                            BankId = 4,
                            CustomerType = 1,
                            InterestRate = 3.10m,
                            IsActive = true,
                            LoanTypeId = 2,
                            MaxAmount = 150000m,
                            MaxTerm = 24,
                            MinAmount = 2000m,
                            MinTerm = 3,
                            Name = "Eğitim Destek Kredisi"
                        },
                        new
                        {
                            Id = 3,
                            BankId = 7,
                            CustomerType = 1,
                            InterestRate = 3.20m,
                            IsActive = true,
                            LoanTypeId = 2,
                            MaxAmount = 100000m,
                            MaxTerm = 18,
                            MinAmount = 5000m,
                            MinTerm = 3,
                            Name = "Öğrenci Eğitim Finansmanı"
                        },
                        new
                        {
                            Id = 4,
                            BankId = 10,
                            CustomerType = 1,
                            InterestRate = 3.35m,
                            IsActive = true,
                            LoanTypeId = 1,
                            MaxAmount = 75000m,
                            MaxTerm = 18,
                            MinAmount = 5000m,
                            MinTerm = 3,
                            Name = "Genç İhtiyaç Kredisi"
                        },
                        new
                        {
                            Id = 5,
                            BankId = 2,
                            CustomerType = 2,
                            InterestRate = 2.85m,
                            IsActive = true,
                            LoanTypeId = 3,
                            MaxAmount = 750000m,
                            MaxTerm = 36,
                            MinAmount = 25000m,
                            MinTerm = 3,
                            Name = "Esnaf Destek Kredisi"
                        },
                        new
                        {
                            Id = 6,
                            BankId = 3,
                            CustomerType = 2,
                            InterestRate = 2.95m,
                            IsActive = true,
                            LoanTypeId = 3,
                            MaxAmount = 500000m,
                            MaxTerm = 36,
                            MinAmount = 20000m,
                            MinTerm = 3,
                            Name = "Esnaf İşletme Kredisi"
                        },
                        new
                        {
                            Id = 7,
                            BankId = 8,
                            CustomerType = 2,
                            InterestRate = 3.05m,
                            IsActive = true,
                            LoanTypeId = 3,
                            MaxAmount = 400000m,
                            MaxTerm = 24,
                            MinAmount = 25000m,
                            MinTerm = 3,
                            Name = "Esnaf Nakit Destek"
                        },
                        new
                        {
                            Id = 8,
                            BankId = 5,
                            CustomerType = 2,
                            InterestRate = 3.40m,
                            IsActive = true,
                            LoanTypeId = 1,
                            MaxAmount = 250000m,
                            MaxTerm = 24,
                            MinAmount = 10000m,
                            MinTerm = 3,
                            Name = "Esnaf İhtiyaç Kredisi"
                        },
                        new
                        {
                            Id = 9,
                            BankId = 6,
                            CustomerType = 2,
                            InterestRate = 3.00m,
                            IsActive = true,
                            LoanTypeId = 3,
                            MaxAmount = 600000m,
                            MaxTerm = 36,
                            MinAmount = 25000m,
                            MinTerm = 3,
                            Name = "KOBİ Esnaf Destek"
                        },
                        new
                        {
                            Id = 10,
                            BankId = 1,
                            CustomerType = 3,
                            InterestRate = 2.95m,
                            IsActive = true,
                            LoanTypeId = 4,
                            MaxAmount = 250000m,
                            MaxTerm = 24,
                            MinAmount = 5000m,
                            MinTerm = 3,
                            Name = "Emekli İhtiyaç Kredisi"
                        },
                        new
                        {
                            Id = 11,
                            BankId = 4,
                            CustomerType = 3,
                            InterestRate = 3.00m,
                            IsActive = true,
                            LoanTypeId = 4,
                            MaxAmount = 200000m,
                            MaxTerm = 24,
                            MinAmount = 5000m,
                            MinTerm = 3,
                            Name = "Emekliye Özel Kredi"
                        },
                        new
                        {
                            Id = 12,
                            BankId = 3,
                            CustomerType = 3,
                            InterestRate = 2.90m,
                            IsActive = true,
                            LoanTypeId = 4,
                            MaxAmount = 250000m,
                            MaxTerm = 24,
                            MinAmount = 5000m,
                            MinTerm = 3,
                            Name = "Emekli Destek Kredisi"
                        },
                        new
                        {
                            Id = 13,
                            BankId = 9,
                            CustomerType = 3,
                            InterestRate = 3.25m,
                            IsActive = true,
                            LoanTypeId = 1,
                            MaxAmount = 150000m,
                            MaxTerm = 18,
                            MinAmount = 5000m,
                            MinTerm = 3,
                            Name = "Emekli İhtiyaç Finansmanı"
                        });
                });

            modelBuilder.Entity("internLoanProject.Domain.Entities.LoanType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BsmvRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KkdfRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LoanTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BsmvRate = 15m,
                            KkdfRate = 15m,
                            Name = "İhtiyaç Kredisi"
                        },
                        new
                        {
                            Id = 2,
                            BsmvRate = 15m,
                            KkdfRate = 15m,
                            Name = "Eğitim Kredisi"
                        },
                        new
                        {
                            Id = 3,
                            BsmvRate = 5m,
                            KkdfRate = 0m,
                            Name = "Esnaf Kredisi"
                        },
                        new
                        {
                            Id = 4,
                            BsmvRate = 15m,
                            KkdfRate = 15m,
                            Name = "Emekli Kredisi"
                        });
                });

            modelBuilder.Entity("internLoanProject.Domain.Entities.PaymentPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BsmvAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InstallmentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("InterestAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KkdfAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoanCalculationId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrincipalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RemainingPrincipal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LoanCalculationId");

                    b.ToTable("PaymentPlans");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("internLoanProject.Domain.Entities.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("internLoanProject.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("internLoanProject.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("internLoanProject.Domain.Entities.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("internLoanProject.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("internLoanProject.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("internLoanProject.Domain.Entities.Identity.AppUser", b =>
                {
                    b.HasOne("internLoanProject.Domain.Entities.Customer", "Customer")
                        .WithOne()
                        .HasForeignKey("internLoanProject.Domain.Entities.Identity.AppUser", "CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("internLoanProject.Domain.Entities.LoanApplication", b =>
                {
                    b.HasOne("internLoanProject.Domain.Entities.Customer", "Customer")
                        .WithMany("LoanApplications")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("internLoanProject.Domain.Entities.LoanCalculation", "LoanCalculation")
                        .WithOne("LoanApplication")
                        .HasForeignKey("internLoanProject.Domain.Entities.LoanApplication", "LoanCalculationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("internLoanProject.Domain.Entities.LoanProduct", "LoanProduct")
                        .WithMany("LoanApplications")
                        .HasForeignKey("LoanProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("LoanCalculation");

                    b.Navigation("LoanProduct");
                });

            modelBuilder.Entity("internLoanProject.Domain.Entities.LoanCalculation", b =>
                {
                    b.HasOne("internLoanProject.Domain.Entities.LoanProduct", "LoanProduct")
                        .WithMany("LoanCalculations")
                        .HasForeignKey("LoanProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoanProduct");
                });

            modelBuilder.Entity("internLoanProject.Domain.Entities.LoanProduct", b =>
                {
                    b.HasOne("internLoanProject.Domain.Entities.Bank", "Bank")
                        .WithMany("LoanProducts")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("internLoanProject.Domain.Entities.LoanType", "LoanType")
                        .WithMany("LoanProducts")
                        .HasForeignKey("LoanTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("LoanType");
                });

            modelBuilder.Entity("internLoanProject.Domain.Entities.PaymentPlan", b =>
                {
                    b.HasOne("internLoanProject.Domain.Entities.LoanCalculation", "LoanCalculation")
                        .WithMany("PaymentPlans")
                        .HasForeignKey("LoanCalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanCalculation");
                });

            modelBuilder.Entity("internLoanProject.Domain.Entities.Bank", b =>
                {
                    b.Navigation("LoanProducts");
                });

            modelBuilder.Entity("internLoanProject.Domain.Entities.Customer", b =>
                {
                    b.Navigation("LoanApplications");
                });

            modelBuilder.Entity("internLoanProject.Domain.Entities.LoanCalculation", b =>
                {
                    b.Navigation("LoanApplication")
                        .IsRequired();

                    b.Navigation("PaymentPlans");
                });

            modelBuilder.Entity("internLoanProject.Domain.Entities.LoanProduct", b =>
                {
                    b.Navigation("LoanApplications");

                    b.Navigation("LoanCalculations");
                });

            modelBuilder.Entity("internLoanProject.Domain.Entities.LoanType", b =>
                {
                    b.Navigation("LoanProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
