<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7d68a334-52f3-49be-aef9-a530b39c0438</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.29" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\internLoanProjectAPI.Persistence\internLoanProjectAPI.Persistence.csproj" />
    <ProjectReference Include="..\..\Infrastructure\internLoanProjectAPI.SignalR\internLoanProjectAPI.SignalR.csproj" />
    <ProjectReference Include="..\..\Infrastructure\RabbitMQ\internLoanProjectAPI.RabbitMQ.csproj" />
  </ItemGroup>

</Project>
