<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOs\Calculation\" />
    <Folder Include="Repositories\CustomerType\" />
    <Folder Include="Repositories\LoanApplication\" />
    <Folder Include="Repositories\LoanCalculation\" />
    <Folder Include="Repositories\LoanProduct\" />
    <Folder Include="Repositories\LoanType\" />
    <Folder Include="Repositories\PaymentPlan\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="DTOs\Common\BankDto.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.29" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\internLoanProject.Domain\internLoanProject.Domain.csproj" />
  </ItemGroup>

</Project>
